### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by ccjmne** [p91paul/middleclickclose#51] opened 2024-03-24 21:58 UTC
Thanks for this excellent extension!

It would be awesome to support Gnome 46, which was released very recently and (I believe) will ship with Ubuntu 24.04 next month!
I'm currently using 46, please let me know if there's anything I can do to help with porting it to this new version.

Cheers!

**Comment by dreua** [comment] 2024-03-25 13:31
You could try adding 46 in metadata.json, it might just work.

**Comment by ccjmne** [comment] 2024-03-25 16:48
Thanks @dreua, I can confirm that it works splendidly.

```shell
sed 's/"45"/"45", "46"/' -i ~/.local/share/gnome-shell/extensions/middleclickclose@paolo.tranquilli.gmail.com/metadata.json
```

**Comment by dreua** [comment] 2024-03-25 18:11
This this is probably just a matter of a PR/change and another release to gnome extensions.

**Comment by gtsiam** [comment] 2024-03-25 20:22
I haven't had the time to make the release just yet, but you should see it by the end of the week.

**Comment by gtsiam** [comment] 2024-03-30 07:10
I can't reproduce the bug right now, but I'll keep an eye on it. I haven't definitively tracked it down to this extension, but the implementation is somewhat hacky by necessity, so it might be some interaction with another extension. If anyone runs into something like this (or being unable to click overview windows), please file an issue. Even if it fixes itself after a reboot.

I've sent the extension for [review](https://extensions.gnome.org/review/53074) on EGO, so when that passes I'm closing the issue.

For packagers: tag `v30` is already available.

**Closed** 2024-03-30 09:48 UTC

**Comment by ccjmne** [comment] 2024-03-30 12:09
Excellent, thank you @gtsiam!
Did you end up figuring out what caused the problem you were experiencing? :)

**Comment by gtsiam** [comment] 2024-03-30 15:48
Nope, no idea. I suspect it's some weird interaction with the extensions I was using at that point, but I cant reproduce it for now.

I was running the extension all week, but I didnt run into it. So I'm calling it fine for now.

If anyone has run into it, (even from memory) do let me know. At this point I'm not even sure if it is a bug of this extension or another... I was too lazy to debug this when it happened, so here I am scratching my head.

If you're curious, here's the [likely culprit](https://github.com/p91paul/middleclickclose/blob/168768a364fbf756495d76ec1f0dde07f0df4392/src/extension.js#L57).

**Comment by ccjmne** [comment] 2024-03-30 16:02
Ah yeah, it was merely out of curiosity! I've been using middleclickclose all week as well without a hitch.

Thanks again!
