### ISSUE TITLE
Overview window animation freezes when moving mouse over the animation area and using 'Rearange delay = 0'

### ISSUE THREAD

**Issue by cyberalex4life** [p91paul/middleclickclose#3] opened 2015-08-08 06:31 UTC
In Gnome Shell 3.16 (Manjaro), when setting 'Rearange delay' to '0' and I go to overview mode by moving mouse to up left corner, then moving mouse to the center of the screen while the animation is yet from being finished, the animation freezes. This looks like this:
![dscf3401](https://cloud.githubusercontent.com/assets/2423189/9149375/95ed4482-3daf-11e5-9893-84a61fcc404e.JPG)
The issue relates to this extension for sure, as I tried disabling all other extensions, then activated one by one testing each time. Also, this glitch will not happen for non zero values: 50 or better 100.
I'm reporting this because I haven't had this problem with earlier versions of Gnome Shell (3.10 to 3.14).
Thank you, I hope you are not upset :)

PS: While freezing occurs, nothing works (volume keys, shortcuts) but when moving the cursor out of the animation area, the animation ends and if I pressed some keys, during the freeze, to search in the overview, the keys appear as typed and things return to normal.

**Comment by p91paul** [comment] 2015-08-08 07:28
Thank you for reporting the bug! Of course I'm not upset, the bug tracker is there to be used :D 

I don't guarantee any timing for this issue, as I'm quite busy at the moment. I'll try to reproduce ASAP, and if I find an easy fix I'll apply it. If someone else is a developer and sees this bug, I'd be happy to accept patches.

A small disclaimer: I'm not the developer of this extension, I'm just maintaining it to keep it up-to-date with gnome-shell versions as the original developer doesn't have time anymore. So this will be the first time I actually get my hands on the code :D

**Comment by p91paul** [comment] 2015-10-03 22:14
could you please try the master branch now? I could not reproduce, but I now add 1 to rearrange delay so that 0 actually means 1ms. I don't think umans can see the difference from 1ms to 0ms.

**Comment by p91paul** [comment] 2015-10-03 22:14
https://github.com/p91paul/middleclickclose/commit/8843ff609be748193f1fbef02bca0d67d6fc7960

**Comment by cyberalex4life** [comment] 2015-10-04 07:10
Seems like the workaround works, 1ms is not noticeable.

**Comment by cyberalex4life** [comment] 2015-10-04 07:18
I don't know if you have time or not, but if you would like to play with this extensions, you  could allow other values than (0, 50, 100, 150 ...). 
Anyway, thanks for your work.

**Comment by p91paul** [comment] 2015-10-06 20:58
Fixed in https://github.com/p91paul/middleclickclose/commit/5f06f1c58856700187a4cd6bb851016ac1b62657

step of +/- buttons is still 50, but now you can write in the box any number.

**Closed by p91paul** 2015-10-06 20:58 UTC
