### ISSUE TITLE
Breaks overview after lock-unlock

### ISSUE THREAD

**Issue by devanubis** [p91paul/middleclickclose#33] opened 2022-03-12 00:03 UTC
I've encountered a problem with my Debain 11 system running Gnome 3.38..6, where after locking and unlocking, the gnome overview is entirely blank (showing no open windows) and I'm unable to exit the overview to return to applications.

Because I'm using Wayland I'm unable to restart the shell, so the only route is to log out and back in to get back to a usable shell.

I've tracked it down to this extension by disabling and re-enabling each in turn.

No idea what could be causing it, I couldn't find anything in syslog indicating what's going on.

Interestingly I'm running the same version of Gnome on another mahcine using Xorg and don't get this problem with this extension. Happy to try reproducing and debugging.

**Comment by p91paul** [comment] 2022-03-12 09:24
How did you install? if from git master, I must warn you that this repo has been modified to support gnome 40/41, dropping 3.38.
Try installing from extensions.gnome.org; if you already did, please reproduce and send error log (gnome logs in journalctl).

**Comment by devanubis** [comment] 2022-03-14 22:16
Hi, yes I was installing from extensions.gnome.org, version in \`metadata.json\` was \`17\`.

I'll grab logs now.

**Comment by devanubis** [comment] 2022-03-14 22:16
Hi, yes I was installing from extensions.gnome.org, version in \`metadata.json\` was \`17\`.

I'll grab logs now.

**Comment by devanubis** [comment] 2022-03-14 23:12
Hmmm... can't reproduce it now with only MiddleClickClose enabled...

My journalctl logs do show some errors from [WindowNavigator](https://extensions.gnome.org/extension/10/windownavigator/) at around the time I was investigating this last Friday... but I definitely isolated every extension and went through them one by one enabling and disabling them...

And now enabling MiddleClickClose and WindowNavigator together or separately neither reproduces this neither with manuall locking, timeout-locking or suspend (all 3 of which caused this before).

Feel free to close this one for now, I'll try reproducing it more in the week and grab some definite logs of when it happens, but it's clearly not nearly as simple as I thought...

**Comment by p91paul** [comment] 2022-03-15 06:27
Thanks for your additional tests!

**Comment by devanubis** [comment] 2022-03-26 22:15
Hi, after several days of not experiencing this, I've ran into it again tonight and it's definitely from within this plugin:

```
Mar 26 22:01:23 HOSTNAME gnome-shell[2366]: JS ERROR: Exception in callback for signal: trigger: too much recursion
                                           enable/Workspace.Workspace.prototype._addWindowClone@/home/USER/.local/share/gnome-shell/extensions/middleclickclose@paolo.tranquilli.gmail.com/extension.js:83:1
                                           _addWindowClone@/home/USER/.local/share/gnome-shell/extensions/windowsNavigator@gnome-shell-extensions.gcampax.github.com/extension.js:73:29
...
```
And that recursion repeats until it's caught.

As before, I have:
- Gnome `3.38.6` (Debain 11 Bullseye, so includes some Debain patches)
- MiddleClickClose version: `17` (from metadata.json generated by SweetTooth) installed from extensions.gnome.org

**Comment by p91paul** [comment] 2022-04-30 14:01
it does look like the WindowsNavigator extension calls _addWindowClone which I override. There could be some incompatibility between the 2 extensions. Did you try contacting the WindowsNavigator author about this?

**Comment by devanubis** [comment] 2022-04-30 15:42
No I haven't contacted them about this yet.

**Comment by p91paul** [comment] 2023-03-13 23:02
Closing this because it's caused by another extension.

**Closed by p91paul** 2023-03-13 23:02 UTC
